### ISSUE TITLE
ng g module [module-name]

### ISSUE THREAD

**Issue by nik-lus** [littleuniversestudios/angular-cli-tools#1]
If there is no module name [module-name] present when using **'ng g m'** command use the folder name the command is run in as the module name.

Example: 
If in '**/src/app/nav-bar'**
and run command **'ng g m'**
 it should create a module in the current directory called **'nav-bar.module.ts'** 
(+ it needs to update index.ts to 'export \* from './nav-bar.module';'

**Comment by mdodds-lus** [comment]
Added in v.1.0.3
