### ISSUE TITLE
Ability to set a prefix for generated components

### ISSUE THREAD

**Issue by itsJess1ca** [littleuniversestudios/angular-cli-tools#10]
I may be missing it, but is there a way to set a prefix for generated components, as the default CLI does?

ie: `ng g my-component` would create `app-my-component` (by default, atleast)

It's a concept me and my team agreed upon and while it's trivial to do it manually, would be a nice addition when generating new components :)

Thanks!

**Comment by nvitas** [comment]
Good idea @j3ddesign. 
we are back in the saddle after the holiday break we'll get right on it. 

I've stopped using the official CLI since we wrote this but maybe you can clarify for me... Is it just the selector that gets the prefix or is the the selector, the file names  and the folder? 

Option A: "my-component" with prefix: "app" creates:
- my-component.ts
- myComponentClass
- selector: 'app-my-component'

or

Option B: "my-component" with prefix: "app" creates:
- app-my-component.ts
- appMyComponentClass
- selector: 'app-my-component'

**Comment by itsJess1ca** [comment]
It would just be the selector that gets the prefix

For example my project uses the prefix "l1"
I'd get 
- selector: 'l1-my-component'
- my-component.ts
- class MyComponent

Hope that clears it up :)

**Comment by nvitas** [comment]
Yep, that clears it up @j3ddesign !

I wasn't sure how the official CLI did it but in this case you have the ability to set the prefix of the selector right now without having to wait for an new update.

If you already have an "angular-cli-tools" folder open it and inside you'll find a "templates" folder. Open that one and inside you'll find a "component.ts" template file.

If you don't have a "angular-cli-tools" folder in your project just run: **ngt install** and it will add it for you, then just follow the same steps.

Inside the "component.ts" file you'll see:

@Component({
    selector: '$name$',
    templateUrl: '$name$.component.html',
    styleUrls: ['$name$.component.$styleFileType$'],
})

just add your prefix in the "selector" property there:

@Component({
    selector: '**app-**$name$',
    templateUrl: '$name$.component.html',
    styleUrls: ['$name$.component.$styleFileType$'],
})

You can change the template (or any other templates found in there) any which way you choose to match your project's needs. When generating components those are the templates being used so feel free to experiment.

Finally, you should probably add the "angular-cli-tools" to your .gitignore file as you don't want to include the templates in your project.

**Comment by itsJess1ca** [comment]
That's exactly what I'm doing now actually, It's working well, just would be nice to be able to set it up in one place instead of editing all templates per project :) 
Thanks for all the great work so far, It's such a great utility

**Comment by nvitas** [comment]
Glad you like it.

We'll add a global selector prefix in the config that will be used across the board plus we'll add a CLI flag (--prefix:my-prefix)  in case you need to change the prefix quickly for a specific element.

Also, if you have any other feature requests feel free to add them as issues on the project, we're always looking for ideas on what to add next.
