### ISSUE TITLE
Changes on the customVariables

### ISSUE THREAD

**Issue by DincaRoberto** [littleuniversestudios/angular-cli-tools#17]
Great tool, guys... 

Can you, please, tell me how to perform some changes on the customVariables?

For example: 

``` 
"customVariables" : {
   "#ModuleName": "MyLoggingModule"
}
```
=> 

Displayed as: ```MY_LOGGING_MODULE``` or ```myLogging``` or ```myLogging-Module```

Are there any functions supported for this type of operations? or maybe a language? 

Thank you, 
Roberto

**Comment by marktdodds** [comment]
check out https://github.com/littleuniversestudios/angular-cli-tools#custom-variables-v110, let me know if you still have questions
