### ISSUE TITLE
add support for spec files

### ISSUE THREAD

**Issue by vsternbach** [littleuniversestudios/angular-cli-tools#21]
Hello again
Is it possible to add support for spec file generation ?

**Comment by nvitas** [comment]
Will merge asap. Thanks for contributing

**Comment by vsternbach** [comment]
Still don't see merged functionality on npm update, have you published a new version to npm registry?

**Comment by mdodds-lus** [comment]
just updated the npm registry

**Comment by vsternbach** [comment]
great, thank you!
