### ISSUE TITLE
Unable to create ngt project

### ISSUE THREAD

**Issue by GitPilot** [littleuniversestudios/angular-cli-tools#7]
When running following command

ngt new PROJECT-NAME --bootstrap

I get the followning error

create-commands.js:10 var pathData = blueprint.extractNameData(projectDestination);
TypeError: blueprint.extractNameData is not a function
at Object.createCommands.newProject

**Comment by GitPilot** [comment]
Please check "blueprint.extractNameData(blueprintName)" references in code, they are not valid anymore.

**Comment by nik-lus** [comment]
Error was created by the previous refactor but is now fixes with the v1.4 release. 

'npm i angular-cli-tools'  will fix the problem with the update

Valid test suite up next on the agenda so that this doesn't happen again. 

Thanks for the heads up.
